#+TITLE:   Thesis Work: A short feedback report
#+AUTHOR:  Konstantinos Sotiropoulos
#+EMAIL:   kisp@kth.se
#+STARTUP: overview
#+OPTIONS: toc:nil email:1
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[T1]{fontenc}

* Overview
To begin with, I would like to thank  my manager Björn Run\r{a}ker 
for giving me the great opportunity of conducting my thesis work in Intel.
Working at Intel is a dream come true, and I believe that by achieving this I have made a major breakthrough in my career.

* Feedback
*Working Environment:* Intel's Office at Kista is ideally located just behind KTH's ICT department. 
                       This has given me the opportunity of meeting my academic supervisor and examiner on a regular basis.

*Equipment:* I have been provided with an excellent office gear, along with the state of the art in HPC for conducting my experiments; two Xeon Servers equipped 3 Xeon Phi cards.
             Furthermore, I have access to all the latest Intel software, even the one that is not commercially available, like Intel CoFluent Studio.

*Incorporation in the team:* The overall impression has exceeded my initial expectations.
                             To be more specific, I felt that not speaking Swedish would be a major barrier in my incorporation in the team. 
                             This is not the case. I synchronize with my manager on a daily basis and we discuss the challenges I face. 
                             Moreover, my colleagues have been more than willing to help me while establishing a relaxed and friendly atmosphere.

*Motivation:* I feel strongly motivated by the fact that I work in a company with the gravitas of Intel, in a state of the art research field.
              Moreover, being able to participate in the shaping of the topic has made me very strongly engaged in the successful completion of the project.

*Compensation:* I am very pleased to receive a very competitive monthly salary, that makes me even more motivated to face my thesis work with a professional attitude.

* Suggestions for Improvement

*Exposure:* I often get the impression that my colleagues are facing challenging tasks in their every day duties
            but they are too polite and discrete to ask for my assistance.
            They may feel that this would impose an extra burden on my thesis duties.
            I feel that gaining exposure to your chosen profession is within an internship's pedagogical outcomes.
            Thus, I would suggest a minimal and on demand incorporation on some of the team's tasks in my workflow.

*Training:* I have the impression that the art of Transaction Level Modeling (TLM) in SystemC is still in its infancy and the literature is quite limited. 
            However, the training company [[https://www.doulos.com/][Doulos]] offers highly specialized [[https://www.doulos.com/content/training/systemc_tlm2.php][training courses in SystemC TLM]].
            The cost of these courses is quite discouraging for me (5000-6000 euros + traveling expenses).
            If I could get at least a partial fund for participating in one of these courses, I believe that the quality of my work would increase.
	    
*Colleague:* I believe that having one more intern here at Intel Sweden would enhance the experience, especially if we could work in the same research field.







