#include <array>
#include "utils.hpp"
#include "mpi.h"
using namespace std;
/* 
   1. Select appropriate data types for time variables
 */







//BEGIN_AUTOGENERATED_SECTION:
#define SIM_DUR 100
//END_AUTOGENERATED_SECTION







/******************************************
 * CLASS: PROCESS
 *****************************************/
template<int NUM_LINES>
class Process {
public:
    Process(array<Line, NUM_LINES>&);
    void eventLoop();
    int  lookahead();
    
private:
    array<Line, NUM_LINES>  inLines;
    int myTime;
};
