#include "process.hpp"





template<int NUM_LINES>
Process<NUM_LINES>::Process(){

//BEGIN_AUTOGENERATED_SECTION:
	inLines[0].rank = 3;  //Line between iss1 and cache
	inLines[1].rank = 4;  //Line between iss1 and memory
	inLines[2].rank = 3;  //Line between iss2 and cache
	inLines[3].rank = 4;  //Line between iss2 and memory
	inLines[4].rank = 4;  //Line between cache and memory
//END_AUTOGENERATED_SECTION

}


template<int NUM_LINES>
void Process<NUM_LINES>::eventLoop(){
    
}





