#include "process.hpp"
#include "utils.hpp"
#include <array>
#include "mpi.h"

using namespace std;






int main(int argc, char *argv[])
{
    int n, myRank, numprocs, i;
    
    MPI_Init(&argc, &argv);
    MPI_Comm_size(MPI_COMM_WORLD, &numprocs);
    MPI_Comm_rank(MPI_COMM_WORLD, &myRank);

    switch (myRank)
    {

//BEGIN_AUTOGENERATED_SECTION:
	case 3:
	{
		array<Line,1> lines;
		lines[0].rank = 4;  //Line between cache1 and memory1
		Process<1> process3(lines); 
	}
	case 1:
	{
		array<Line,1> lines;
		lines[0].rank = 3;  //Line between iss1 and cache1
		Process<1> process1(lines); 
	}
	case 2:
	{
		array<Line,1> lines;
		lines[0].rank = 3;  //Line between iss2 and cache1
		Process<1> process2(lines); 
	}
//END_AUTOGENERATED_SECTION

    default:
	break;
    }

    MPI_Finalize();
    return 0;
}
